export const ADDITEMTOCART = "ADDITEMTOCART";
export const DECREASEITEMINCART = "DECREASEITEMINCART";
export const INCREASEITEMINCART = "INCREASEITEMINCART";
export const REMOVEITEMTOCART = "REMOVEITEMTOCART";